INSERT INTO organization (id, name, slug)
VALUES
    (gen_random_uuid()::TEXT, 'Japan Malaysia Technical Institute (JMTI)', 'jmti'),
    (gen_random_uuid()::TEXT, 'ADTEC Shah Alam', 'adtec-shah-alam'),
    (gen_random_uuid()::TEXT, 'ADTEC Batu Pahat', 'adtec-batu-pahat'),
    (gen_random_uuid()::TEXT, 'ADTEC Kulim', 'adtec-kulim'),
    (gen_random_uuid()::TEXT, 'ADTEC Melaka', 'adtec-melaka'),
    (gen_random_uuid()::TEXT, 'ADTEC Taiping', 'adtec-taiping'),
    (gen_random_uuid()::TEXT, 'ADTEC Kemaman', 'adtec-kemaman'),
    (gen_random_uuid()::TEXT, 'ADTEC Jerantut', 'adtec-jerantut'),
    (gen_random_uuid()::TEXT, 'ADTEC Bintulu', 'adtec-bintulu'),
    (gen_random_uuid()::TEXT, 'ILP Kangar', 'ilp-kangar'),
    (gen_random_uuid()::TEXT, 'ILP Jitra', 'ilp-jitra'),
    (gen_random_uuid()::TEXT, 'ILP Perai', 'ilp-perai'),
    (gen_random_uuid()::TEXT, 'ILP Arumugam Pillai Nibong Tebal', 'ilp-arumugam-pillai-nibong-tebal'),
    (gen_random_uuid()::TEXT, 'ILP Kepala Batas', 'ilp-kepala-batas'),
    (gen_random_uuid()::TEXT, 'ILP Ipoh', 'ilp-ipoh'),
    (gen_random_uuid()::TEXT, 'ILP Kuala Lumpur', 'ilp-kuala-lumpur'),
    (gen_random_uuid()::TEXT, 'ILP Kuala Langat', 'ilp-kuala-langat'),
    (gen_random_uuid()::TEXT, 'ILP Pedas', 'ilp-pedas'),
    (gen_random_uuid()::TEXT, 'ILP Bukit Katil', 'ilp-bukit-katil'),
    (gen_random_uuid()::TEXT, 'ILP Selandar', 'ilp-selandar'),
    (gen_random_uuid()::TEXT, 'ILP Tangkak', 'ilp-tangkak'),
    (gen_random_uuid()::TEXT, 'ILP Pasir Gudang', 'ilp-pasir-gudang'),
    (gen_random_uuid()::TEXT, 'ILP Mersing', 'ilp-mersing'),
    (gen_random_uuid()::TEXT, 'ILP Kuantan', 'ilp-kuantan'),
    (gen_random_uuid()::TEXT, 'ILP Kuala Terengganu', 'ilp-kuala-terengganu'),
    (gen_random_uuid()::TEXT, 'ILP Marang', 'ilp-marang'),
    (gen_random_uuid()::TEXT, 'ILP Kota Bharu', 'ilp-kota-bharu'),
    (gen_random_uuid()::TEXT, 'ILP Kota Samarahan', 'ilp-kota-samarahan'),
    (gen_random_uuid()::TEXT, 'ILP Miri', 'ilp-miri'),
    (gen_random_uuid()::TEXT, 'ILP Kota Kinabalu', 'ilp-kota-kinabalu'),
    (gen_random_uuid()::TEXT, 'ILP Sandakan', 'ilp-sandakan'),
    (gen_random_uuid()::TEXT, 'ILP Labuan', 'ilp-labuan'),
    (gen_random_uuid()::TEXT, 'PROTON Institute ADTEC Melaka', 'proton-institute-adtec-melaka')
ON CONFLICT (slug) DO NOTHING;
