/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedOrganizationRouteImport } from './routes/_protected/organization'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedAcademicRouteImport } from './routes/_protected/academic'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminOrganizationsRouteImport } from './routes/_protected/admin/organizations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationRoute = ProtectedOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAcademicRoute = ProtectedAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminOrganizationsRoute =
  ProtectedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/academic': typeof ProtectedAcademicRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/organization': typeof ProtectedOrganizationRoute
  '/admin/organizations': typeof ProtectedAdminOrganizationsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/academic': typeof ProtectedAcademicRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/organization': typeof ProtectedOrganizationRoute
  '/admin/organizations': typeof ProtectedAdminOrganizationsRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/academic': typeof ProtectedAcademicRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/organization': typeof ProtectedOrganizationRoute
  '/_protected/admin/organizations': typeof ProtectedAdminOrganizationsRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/academic'
    | '/account'
    | '/dashboard'
    | '/organization'
    | '/admin/organizations'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/academic'
    | '/account'
    | '/dashboard'
    | '/organization'
    | '/admin/organizations'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/signup'
    | '/_protected/academic'
    | '/_protected/account'
    | '/_protected/dashboard'
    | '/_protected/organization'
    | '/_protected/admin/organizations'
    | '/_protected/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organization': {
      id: '/_protected/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedOrganizationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/academic': {
      id: '/_protected/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof ProtectedAcademicRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/organizations': {
      id: '/_protected/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof ProtectedAdminOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAcademicRoute: typeof ProtectedAcademicRoute
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOrganizationRoute: typeof ProtectedOrganizationRoute
  ProtectedAdminOrganizationsRoute: typeof ProtectedAdminOrganizationsRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAcademicRoute: ProtectedAcademicRoute,
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOrganizationRoute: ProtectedOrganizationRoute,
  ProtectedAdminOrganizationsRoute: ProtectedAdminOrganizationsRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
