// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAcademicCourse = `-- name: CreateAcademicCourse :one
INSERT INTO academic_course (id, organization_id, code, name, credits)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, code, name, credits, active, created_at, updated_at
`

type CreateAcademicCourseParams struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organization_id"`
	Code           string  `json:"code"`
	Name           string  `json:"name"`
	Credits        float64 `json:"credits"`
}

func (q *Queries) CreateAcademicCourse(ctx context.Context, arg CreateAcademicCourseParams) (AcademicCourse, error) {
	row := q.db.QueryRow(ctx, createAcademicCourse,
		arg.ID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Credits,
	)
	var i AcademicCourse
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAcademicSemester = `-- name: CreateAcademicSemester :one
INSERT INTO academic_semester (id, organization_id, code, name, academic_year, sequence, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, code, name, academic_year, sequence, status, created_at, updated_at
`

type CreateAcademicSemesterParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Code           string `json:"code"`
	Name           string `json:"name"`
	AcademicYear   int32  `json:"academic_year"`
	Sequence       int32  `json:"sequence"`
	Status         string `json:"status"`
}

func (q *Queries) CreateAcademicSemester(ctx context.Context, arg CreateAcademicSemesterParams) (AcademicSemester, error) {
	row := q.db.QueryRow(ctx, createAcademicSemester,
		arg.ID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.AcademicYear,
		arg.Sequence,
		arg.Status,
	)
	var i AcademicSemester
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.AcademicYear,
		&i.Sequence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAcademicStudent = `-- name: CreateAcademicStudent :one
INSERT INTO academic_student (id, organization_id, student_no, name, email, program, intake)
VALUES (
    $1, $2, $3, $4,
    NULLIF($5::TEXT, ''), $6, $7
)
RETURNING id, organization_id, student_no, name, email, program, intake, status, created_at, updated_at
`

type CreateAcademicStudentParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	StudentNo      string `json:"student_no"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Program        string `json:"program"`
	Intake         string `json:"intake"`
}

func (q *Queries) CreateAcademicStudent(ctx context.Context, arg CreateAcademicStudentParams) (AcademicStudent, error) {
	row := q.db.QueryRow(ctx, createAcademicStudent,
		arg.ID,
		arg.OrganizationID,
		arg.StudentNo,
		arg.Name,
		arg.Email,
		arg.Program,
		arg.Intake,
	)
	var i AcademicStudent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentNo,
		&i.Name,
		&i.Email,
		&i.Program,
		&i.Intake,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAcademicGrade = `-- name: FindAcademicGrade :one
SELECT id, organization_id, letter, min_score, max_score, grade_point, passing, sort_order FROM academic_grade_scale
WHERE organization_id = $1 AND $2 BETWEEN min_score AND max_score
ORDER BY sort_order LIMIT 1
`

type FindAcademicGradeParams struct {
	OrganizationID string  `json:"organization_id"`
	MinScore       float64 `json:"min_score"`
}

func (q *Queries) FindAcademicGrade(ctx context.Context, arg FindAcademicGradeParams) (AcademicGradeScale, error) {
	row := q.db.QueryRow(ctx, findAcademicGrade, arg.OrganizationID, arg.MinScore)
	var i AcademicGradeScale
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Letter,
		&i.MinScore,
		&i.MaxScore,
		&i.GradePoint,
		&i.Passing,
		&i.SortOrder,
	)
	return i, err
}

const getAcademicCourse = `-- name: GetAcademicCourse :one
SELECT id, organization_id, code, name, credits, active, created_at, updated_at FROM academic_course WHERE id = $1 AND organization_id = $2
`

type GetAcademicCourseParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetAcademicCourse(ctx context.Context, arg GetAcademicCourseParams) (AcademicCourse, error) {
	row := q.db.QueryRow(ctx, getAcademicCourse, arg.ID, arg.OrganizationID)
	var i AcademicCourse
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcademicMember = `-- name: GetAcademicMember :one
SELECT id, organization_id, user_id, role, created_at, permissions FROM member WHERE organization_id = $1 AND user_id = $2
`

type GetAcademicMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetAcademicMember(ctx context.Context, arg GetAcademicMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getAcademicMember, arg.OrganizationID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}

const getAcademicOrganizationStatus = `-- name: GetAcademicOrganizationStatus :one
SELECT status FROM organization WHERE id = $1
`

func (q *Queries) GetAcademicOrganizationStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getAcademicOrganizationStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getAcademicSemester = `-- name: GetAcademicSemester :one
SELECT id, organization_id, code, name, academic_year, sequence, status, created_at, updated_at FROM academic_semester WHERE id = $1 AND organization_id = $2
`

type GetAcademicSemesterParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetAcademicSemester(ctx context.Context, arg GetAcademicSemesterParams) (AcademicSemester, error) {
	row := q.db.QueryRow(ctx, getAcademicSemester, arg.ID, arg.OrganizationID)
	var i AcademicSemester
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.AcademicYear,
		&i.Sequence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcademicStudent = `-- name: GetAcademicStudent :one
SELECT id, organization_id, student_no, name, email, program, intake, status, created_at, updated_at FROM academic_student WHERE id = $1 AND organization_id = $2
`

type GetAcademicStudentParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetAcademicStudent(ctx context.Context, arg GetAcademicStudentParams) (AcademicStudent, error) {
	row := q.db.QueryRow(ctx, getAcademicStudent, arg.ID, arg.OrganizationID)
	var i AcademicStudent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentNo,
		&i.Name,
		&i.Email,
		&i.Program,
		&i.Intake,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcademicUserRole = `-- name: GetAcademicUserRole :one
SELECT role FROM "user" WHERE id = $1
`

func (q *Queries) GetAcademicUserRole(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getAcademicUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listAcademicCourses = `-- name: ListAcademicCourses :many
SELECT id, organization_id, code, name, credits, active, created_at, updated_at FROM academic_course WHERE organization_id = $1 ORDER BY code
`

func (q *Queries) ListAcademicCourses(ctx context.Context, organizationID string) ([]AcademicCourse, error) {
	rows, err := q.db.Query(ctx, listAcademicCourses, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicCourse{}
	for rows.Next() {
		var i AcademicCourse
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Credits,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcademicGradeScale = `-- name: ListAcademicGradeScale :many
SELECT id, organization_id, letter, min_score, max_score, grade_point, passing, sort_order FROM academic_grade_scale WHERE organization_id = $1 ORDER BY sort_order
`

func (q *Queries) ListAcademicGradeScale(ctx context.Context, organizationID string) ([]AcademicGradeScale, error) {
	rows, err := q.db.Query(ctx, listAcademicGradeScale, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicGradeScale{}
	for rows.Next() {
		var i AcademicGradeScale
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Letter,
			&i.MinScore,
			&i.MaxScore,
			&i.GradePoint,
			&i.Passing,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcademicResultsByStudent = `-- name: ListAcademicResultsByStudent :many
SELECT
    r.id, r.organization_id, r.student_id, r.semester_id, r.course_id, r.score, r.grade, r.grade_point, r.credits, r.created_at, r.updated_at,
    s.code AS semester_code,
    s.name AS semester_name,
    s.academic_year,
    s.sequence AS semester_sequence,
    c.code AS course_code,
    c.name AS course_name
FROM academic_result r
JOIN academic_semester s ON s.id = r.semester_id
JOIN academic_course c ON c.id = r.course_id
WHERE r.organization_id = $1 AND r.student_id = $2
ORDER BY s.academic_year, s.sequence, c.code
`

type ListAcademicResultsByStudentParams struct {
	OrganizationID string `json:"organization_id"`
	StudentID      string `json:"student_id"`
}

type ListAcademicResultsByStudentRow struct {
	ID               string             `json:"id"`
	OrganizationID   string             `json:"organization_id"`
	StudentID        string             `json:"student_id"`
	SemesterID       string             `json:"semester_id"`
	CourseID         string             `json:"course_id"`
	Score            float64            `json:"score"`
	Grade            string             `json:"grade"`
	GradePoint       float64            `json:"grade_point"`
	Credits          float64            `json:"credits"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SemesterCode     string             `json:"semester_code"`
	SemesterName     string             `json:"semester_name"`
	AcademicYear     int32              `json:"academic_year"`
	SemesterSequence int32              `json:"semester_sequence"`
	CourseCode       string             `json:"course_code"`
	CourseName       string             `json:"course_name"`
}

func (q *Queries) ListAcademicResultsByStudent(ctx context.Context, arg ListAcademicResultsByStudentParams) ([]ListAcademicResultsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listAcademicResultsByStudent, arg.OrganizationID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcademicResultsByStudentRow{}
	for rows.Next() {
		var i ListAcademicResultsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentID,
			&i.SemesterID,
			&i.CourseID,
			&i.Score,
			&i.Grade,
			&i.GradePoint,
			&i.Credits,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SemesterCode,
			&i.SemesterName,
			&i.AcademicYear,
			&i.SemesterSequence,
			&i.CourseCode,
			&i.CourseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcademicSemesters = `-- name: ListAcademicSemesters :many
SELECT id, organization_id, code, name, academic_year, sequence, status, created_at, updated_at FROM academic_semester WHERE organization_id = $1 ORDER BY academic_year DESC, sequence DESC
`

func (q *Queries) ListAcademicSemesters(ctx context.Context, organizationID string) ([]AcademicSemester, error) {
	rows, err := q.db.Query(ctx, listAcademicSemesters, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicSemester{}
	for rows.Next() {
		var i AcademicSemester
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.AcademicYear,
			&i.Sequence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcademicStudents = `-- name: ListAcademicStudents :many
SELECT id, organization_id, student_no, name, email, program, intake, status, created_at, updated_at FROM academic_student WHERE organization_id = $1 ORDER BY name, student_no
`

func (q *Queries) ListAcademicStudents(ctx context.Context, organizationID string) ([]AcademicStudent, error) {
	rows, err := q.db.Query(ctx, listAcademicStudents, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicStudent{}
	for rows.Next() {
		var i AcademicStudent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StudentNo,
			&i.Name,
			&i.Email,
			&i.Program,
			&i.Intake,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAcademicResult = `-- name: UpsertAcademicResult :one
INSERT INTO academic_result
    (id, organization_id, student_id, semester_id, course_id, score, grade, grade_point, credits)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (student_id, semester_id, course_id) DO UPDATE SET
    score = EXCLUDED.score,
    grade = EXCLUDED.grade,
    grade_point = EXCLUDED.grade_point,
    credits = EXCLUDED.credits,
    updated_at = NOW()
RETURNING id, organization_id, student_id, semester_id, course_id, score, grade, grade_point, credits, created_at, updated_at
`

type UpsertAcademicResultParams struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organization_id"`
	StudentID      string  `json:"student_id"`
	SemesterID     string  `json:"semester_id"`
	CourseID       string  `json:"course_id"`
	Score          float64 `json:"score"`
	Grade          string  `json:"grade"`
	GradePoint     float64 `json:"grade_point"`
	Credits        float64 `json:"credits"`
}

func (q *Queries) UpsertAcademicResult(ctx context.Context, arg UpsertAcademicResultParams) (AcademicResult, error) {
	row := q.db.QueryRow(ctx, upsertAcademicResult,
		arg.ID,
		arg.OrganizationID,
		arg.StudentID,
		arg.SemesterID,
		arg.CourseID,
		arg.Score,
		arg.Grade,
		arg.GradePoint,
		arg.Credits,
	)
	var i AcademicResult
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StudentID,
		&i.SemesterID,
		&i.CourseID,
		&i.Score,
		&i.Grade,
		&i.GradePoint,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
