// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationAuditLog = `-- name: CreateOrganizationAuditLog :one
INSERT INTO organization_audit_log (
    id, organization_id, actor_user_id, actor_name, actor_email,
    action, target_type, target_id, details
)
SELECT
    $1, $2, u.id, u.name, u.email,
    $3, $4, $5, $6
FROM "user" u
WHERE u.id = $7
RETURNING id, organization_id, actor_user_id, actor_name, actor_email, action, target_type, target_id, details, created_at
`

type CreateOrganizationAuditLogParams struct {
	ID             string      `json:"id"`
	OrganizationID string      `json:"organization_id"`
	Action         string      `json:"action"`
	TargetType     string      `json:"target_type"`
	TargetID       pgtype.Text `json:"target_id"`
	Details        []byte      `json:"details"`
	ActorUserID    string      `json:"actor_user_id"`
}

func (q *Queries) CreateOrganizationAuditLog(ctx context.Context, arg CreateOrganizationAuditLogParams) (OrganizationAuditLog, error) {
	row := q.db.QueryRow(ctx, createOrganizationAuditLog,
		arg.ID,
		arg.OrganizationID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.ActorUserID,
	)
	var i OrganizationAuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorUserID,
		&i.ActorName,
		&i.ActorEmail,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationAuditLogs = `-- name: ListOrganizationAuditLogs :many
SELECT id, organization_id, actor_user_id, actor_name, actor_email, action, target_type, target_id, details, created_at FROM organization_audit_log
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationAuditLogsParams struct {
	OrganizationID string `json:"organization_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListOrganizationAuditLogs(ctx context.Context, arg ListOrganizationAuditLogsParams) ([]OrganizationAuditLog, error) {
	rows, err := q.db.Query(ctx, listOrganizationAuditLogs, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationAuditLog{}
	for rows.Next() {
		var i OrganizationAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.ActorName,
			&i.ActorEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
