// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO "invitation" (id, organization_id, email, role, expires_at, inviter_id)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id
`

type CreateInvitationParams struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	InviterID      string             `json:"inviter_id"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.ExpiresAt,
		arg.InviterID,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InviterID,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM "invitation" WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id FROM "invitation" WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InviterID,
	)
	return i, err
}

const getInvitationForUpdate = `-- name: GetInvitationForUpdate :one
SELECT id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id FROM "invitation" WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetInvitationForUpdate(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationForUpdate, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InviterID,
	)
	return i, err
}

const listInvitationsByEmail = `-- name: ListInvitationsByEmail :many
SELECT id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id FROM "invitation" WHERE email = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TeamID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InviterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByOrganizationID = `-- name: ListInvitationsByOrganizationID :many
SELECT id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id FROM "invitation" WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByOrganizationID(ctx context.Context, organizationID string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TeamID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InviterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE "invitation" SET status=$2 WHERE id=$1 RETURNING id, organization_id, email, role, team_id, status, expires_at, created_at, inviter_id
`

type UpdateInvitationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.InviterID,
	)
	return i, err
}
