// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO "member" (id, organization_id, user_id, role) VALUES ($1, $2, $3, $4) RETURNING id, organization_id, user_id, role, created_at, permissions
`

type CreateMemberParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM "member" WHERE organization_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.OrganizationID, arg.UserID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, organization_id, user_id, role, created_at, permissions FROM "member" WHERE organization_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrganizationID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}

const listMembersByOrganizationID = `-- name: ListMembersByOrganizationID :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, m.permissions, u.name, u.email, u.image FROM "member" m
JOIN "user" u ON u.id = m.user_id
WHERE m.organization_id = $1 ORDER BY u.name
`

type ListMembersByOrganizationIDRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Permissions    []string           `json:"permissions"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Image          pgtype.Text        `json:"image"`
}

func (q *Queries) ListMembersByOrganizationID(ctx context.Context, organizationID string) ([]ListMembersByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listMembersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByOrganizationIDRow{}
	for rows.Next() {
		var i ListMembersByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Permissions,
			&i.Name,
			&i.Email,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberPermissions = `-- name: UpdateMemberPermissions :one
UPDATE member SET permissions = $3 WHERE organization_id = $1 AND user_id = $2 RETURNING id, organization_id, user_id, role, created_at, permissions
`

type UpdateMemberPermissionsParams struct {
	OrganizationID string   `json:"organization_id"`
	UserID         string   `json:"user_id"`
	Permissions    []string `json:"permissions"`
}

func (q *Queries) UpdateMemberPermissions(ctx context.Context, arg UpdateMemberPermissionsParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberPermissions, arg.OrganizationID, arg.UserID, arg.Permissions)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE "member" SET role=$3 WHERE organization_id=$1 AND user_id=$2 RETURNING id, organization_id, user_id, role, created_at, permissions
`

type UpdateMemberRoleParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}
