// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicCourse struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Credits        float64            `json:"credits"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AcademicGradeScale struct {
	ID             string  `json:"id"`
	OrganizationID string  `json:"organization_id"`
	Letter         string  `json:"letter"`
	MinScore       float64 `json:"min_score"`
	MaxScore       float64 `json:"max_score"`
	GradePoint     float64 `json:"grade_point"`
	Passing        bool    `json:"passing"`
	SortOrder      int32   `json:"sort_order"`
}

type AcademicResult struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	StudentID      string             `json:"student_id"`
	SemesterID     string             `json:"semester_id"`
	CourseID       string             `json:"course_id"`
	Score          float64            `json:"score"`
	Grade          string             `json:"grade"`
	GradePoint     float64            `json:"grade_point"`
	Credits        float64            `json:"credits"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AcademicSemester struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	AcademicYear   int32              `json:"academic_year"`
	Sequence       int32              `json:"sequence"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AcademicStudent struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	StudentNo      string             `json:"student_no"`
	Name           string             `json:"name"`
	Email          pgtype.Text        `json:"email"`
	Program        string             `json:"program"`
	Intake         string             `json:"intake"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Account struct {
	ID                    string             `json:"id"`
	AccountID             string             `json:"account_id"`
	ProviderID            string             `json:"provider_id"`
	UserID                string             `json:"user_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	IDToken               pgtype.Text        `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	TeamID         pgtype.Text        `json:"team_id"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	InviterID      string             `json:"inviter_id"`
}

type Member struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Permissions    []string           `json:"permissions"`
}

type Organization struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Logo            pgtype.Text        `json:"logo"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Metadata        pgtype.Text        `json:"metadata"`
	LogoKey         pgtype.Text        `json:"logo_key"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoUpdatedAt   pgtype.Timestamptz `json:"logo_updated_at"`
	Status          string             `json:"status"`
}

type OrganizationAuditLog struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	ActorUserID    pgtype.Text        `json:"actor_user_id"`
	ActorName      string             `json:"actor_name"`
	ActorEmail     string             `json:"actor_email"`
	Action         string             `json:"action"`
	TargetType     string             `json:"target_type"`
	TargetID       pgtype.Text        `json:"target_id"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                   string             `json:"id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Token                string             `json:"token"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	UserID               string             `json:"user_id"`
	ImpersonatedBy       pgtype.Text        `json:"impersonated_by"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	ActiveTeamID         pgtype.Text        `json:"active_team_id"`
}

type Team struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	ID        string             `json:"id"`
	TeamID    string             `json:"team_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	EmailVerified     bool               `json:"email_verified"`
	Image             pgtype.Text        `json:"image"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Role              string             `json:"role"`
	Banned            bool               `json:"banned"`
	BanReason         pgtype.Text        `json:"ban_reason"`
	BanExpires        pgtype.Timestamptz `json:"ban_expires"`
	TwoFactorEnabled  bool               `json:"two_factor_enabled"`
	AvatarKey         pgtype.Text        `json:"avatar_key"`
	AvatarContentType pgtype.Text        `json:"avatar_content_type"`
	AvatarUpdatedAt   pgtype.Timestamptz `json:"avatar_updated_at"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
