// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO "organization" (id, name, slug, logo, metadata) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status
`

type CreateOrganizationParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Logo     pgtype.Text `json:"logo"`
	Metadata pgtype.Text `json:"metadata"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Metadata,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM "organization" WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const demoteOrganizationOwners = `-- name: DemoteOrganizationOwners :exec
UPDATE member
SET role = 'admin'
WHERE organization_id = $1 AND role = 'owner' AND user_id <> $2
`

type DemoteOrganizationOwnersParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) DemoteOrganizationOwners(ctx context.Context, arg DemoteOrganizationOwnersParams) error {
	_, err := q.db.Exec(ctx, demoteOrganizationOwners, arg.OrganizationID, arg.UserID)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status FROM "organization" WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status FROM "organization" WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const getOrganizationOwner = `-- name: GetOrganizationOwner :one
SELECT u.id, u.name, u.email, u.image
FROM member m
JOIN "user" u ON u.id = m.user_id
WHERE m.organization_id = $1 AND m.role = 'owner'
ORDER BY m.created_at, m.id
LIMIT 1
`

type GetOrganizationOwnerRow struct {
	ID    string      `json:"id"`
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Image pgtype.Text `json:"image"`
}

func (q *Queries) GetOrganizationOwner(ctx context.Context, organizationID string) (GetOrganizationOwnerRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationOwner, organizationID)
	var i GetOrganizationOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Image,
	)
	return i, err
}

const getOrganizationStatus = `-- name: GetOrganizationStatus :one
SELECT status FROM organization WHERE id = $1
`

func (q *Queries) GetOrganizationStatus(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listOrganizationMembershipsByUserID = `-- name: ListOrganizationMembershipsByUserID :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at, o.metadata, o.logo_key, o.logo_content_type, o.logo_updated_at, o.status, m.role AS membership_role
FROM "organization" o
JOIN "member" m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

type ListOrganizationMembershipsByUserIDRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Logo            pgtype.Text        `json:"logo"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Metadata        pgtype.Text        `json:"metadata"`
	LogoKey         pgtype.Text        `json:"logo_key"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoUpdatedAt   pgtype.Timestamptz `json:"logo_updated_at"`
	Status          string             `json:"status"`
	MembershipRole  string             `json:"membership_role"`
}

func (q *Queries) ListOrganizationMembershipsByUserID(ctx context.Context, userID string) ([]ListOrganizationMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembershipsByUserIDRow{}
	for rows.Next() {
		var i ListOrganizationMembershipsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.Metadata,
			&i.LogoKey,
			&i.LogoContentType,
			&i.LogoUpdatedAt,
			&i.Status,
			&i.MembershipRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status FROM organization ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.Metadata,
			&i.LogoKey,
			&i.LogoContentType,
			&i.LogoUpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUserID = `-- name: ListOrganizationsByUserID :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at, o.metadata, o.logo_key, o.logo_content_type, o.logo_updated_at, o.status FROM "organization" o
JOIN "member" m ON m.organization_id = o.id
WHERE m.user_id = $1 ORDER BY o.name
`

func (q *Queries) ListOrganizationsByUserID(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.Metadata,
			&i.LogoKey,
			&i.LogoContentType,
			&i.LogoUpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsWithOwner = `-- name: ListOrganizationsWithOwner :many
SELECT
    o.id, o.name, o.slug, o.logo, o.created_at, o.metadata, o.logo_key, o.logo_content_type, o.logo_updated_at, o.status,
    owner_user.id AS owner_id,
    owner_user.name AS owner_name,
    owner_user.email AS owner_email,
    owner_user.image AS owner_image
FROM organization o
LEFT JOIN member owner_member ON owner_member.id = (
    SELECT m.id
    FROM member m
    WHERE m.organization_id = o.id AND m.role = 'owner'
    ORDER BY m.created_at, m.id
    LIMIT 1
)
LEFT JOIN "user" owner_user ON owner_user.id = owner_member.user_id
ORDER BY o.name
`

type ListOrganizationsWithOwnerRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Logo            pgtype.Text        `json:"logo"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Metadata        pgtype.Text        `json:"metadata"`
	LogoKey         pgtype.Text        `json:"logo_key"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoUpdatedAt   pgtype.Timestamptz `json:"logo_updated_at"`
	Status          string             `json:"status"`
	OwnerID         pgtype.Text        `json:"owner_id"`
	OwnerName       pgtype.Text        `json:"owner_name"`
	OwnerEmail      pgtype.Text        `json:"owner_email"`
	OwnerImage      pgtype.Text        `json:"owner_image"`
}

func (q *Queries) ListOrganizationsWithOwner(ctx context.Context) ([]ListOrganizationsWithOwnerRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsWithOwnerRow{}
	for rows.Next() {
		var i ListOrganizationsWithOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.Metadata,
			&i.LogoKey,
			&i.LogoContentType,
			&i.LogoUpdatedAt,
			&i.Status,
			&i.OwnerID,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.OwnerImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedOrganizationsByUserID = `-- name: ListOwnedOrganizationsByUserID :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at, o.metadata, o.logo_key, o.logo_content_type, o.logo_updated_at, o.status FROM "organization" o
JOIN "member" m ON m.organization_id = o.id
WHERE m.user_id = $1 AND m.role = 'owner'
ORDER BY o.name
`

func (q *Queries) ListOwnedOrganizationsByUserID(ctx context.Context, userID string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOwnedOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.Metadata,
			&i.LogoKey,
			&i.LogoContentType,
			&i.LogoUpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganization = `-- name: LockOrganization :one
SELECT id FROM organization WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOrganization(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockOrganization, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE "organization" SET name=$2, slug=$3, logo=COALESCE($4, logo), metadata=$5 WHERE id=$1 RETURNING id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status
`

type UpdateOrganizationParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Logo     pgtype.Text `json:"logo"`
	Metadata pgtype.Text `json:"metadata"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Metadata,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const updateOrganizationLogo = `-- name: UpdateOrganizationLogo :one
UPDATE "organization"
SET logo=$2, logo_key=$3, logo_content_type=$4, logo_updated_at=$5
WHERE id=$1
RETURNING id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status
`

type UpdateOrganizationLogoParams struct {
	ID              string             `json:"id"`
	Logo            pgtype.Text        `json:"logo"`
	LogoKey         pgtype.Text        `json:"logo_key"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoUpdatedAt   pgtype.Timestamptz `json:"logo_updated_at"`
}

func (q *Queries) UpdateOrganizationLogo(ctx context.Context, arg UpdateOrganizationLogoParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationLogo,
		arg.ID,
		arg.Logo,
		arg.LogoKey,
		arg.LogoContentType,
		arg.LogoUpdatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :one
UPDATE organization SET status = $2 WHERE id = $1 RETURNING id, name, slug, logo, created_at, metadata, logo_key, logo_content_type, logo_updated_at, status
`

type UpdateOrganizationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationStatus, arg.ID, arg.Status)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
		&i.Metadata,
		&i.LogoKey,
		&i.LogoContentType,
		&i.LogoUpdatedAt,
		&i.Status,
	)
	return i, err
}

const upsertOrganizationOwner = `-- name: UpsertOrganizationOwner :one
INSERT INTO member (id, organization_id, user_id, role)
VALUES ($1, $2, $3, 'owner')
ON CONFLICT (organization_id, user_id)
DO UPDATE SET role = 'owner'
RETURNING id, organization_id, user_id, role, created_at, permissions
`

type UpsertOrganizationOwnerParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpsertOrganizationOwner(ctx context.Context, arg UpsertOrganizationOwnerParams) (Member, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationOwner, arg.ID, arg.OrganizationID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}
