// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActiveOrganizationForMember = `-- name: ClearActiveOrganizationForMember :exec
UPDATE "session"
SET active_organization_id = NULL, active_team_id = NULL, updated_at = NOW()
WHERE active_organization_id = $1 AND user_id = $2
`

type ClearActiveOrganizationForMemberParams struct {
	ActiveOrganizationID pgtype.Text `json:"active_organization_id"`
	UserID               string      `json:"user_id"`
}

func (q *Queries) ClearActiveOrganizationForMember(ctx context.Context, arg ClearActiveOrganizationForMemberParams) error {
	_, err := q.db.Exec(ctx, clearActiveOrganizationForMember, arg.ActiveOrganizationID, arg.UserID)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO "session" (id, expires_at, token, ip_address, user_agent, user_id, active_organization_id, active_team_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id
`

type CreateSessionParams struct {
	ID                   string             `json:"id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Token                string             `json:"token"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	UserID               string             `json:"user_id"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	ActiveTeamID         pgtype.Text        `json:"active_team_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
		arg.ActiveOrganizationID,
		arg.ActiveTeamID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM "session" WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM "session" WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM "session" WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id FROM "session" WHERE token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
	)
	return i, err
}

const getSessionContextByToken = `-- name: GetSessionContextByToken :one
SELECT s.id, s.expires_at, s.token, s.created_at, s.updated_at, s.ip_address, s.user_agent, s.user_id, s.impersonated_by, s.active_organization_id, s.active_team_id, COALESCE(
  m.role,
  CASE WHEN s.active_organization_id IS NOT NULL AND u.role = 'admin' THEN 'admin' END,
  ''
) AS active_organization_role
FROM "session" s
JOIN "user" u ON u.id = s.user_id
LEFT JOIN "member" m
  ON m.organization_id = s.active_organization_id
 AND m.user_id = s.user_id
WHERE s.token = $1
`

type GetSessionContextByTokenRow struct {
	ID                     string             `json:"id"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	Token                  string             `json:"token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	IpAddress              pgtype.Text        `json:"ip_address"`
	UserAgent              pgtype.Text        `json:"user_agent"`
	UserID                 string             `json:"user_id"`
	ImpersonatedBy         pgtype.Text        `json:"impersonated_by"`
	ActiveOrganizationID   pgtype.Text        `json:"active_organization_id"`
	ActiveTeamID           pgtype.Text        `json:"active_team_id"`
	ActiveOrganizationRole string             `json:"active_organization_role"`
}

func (q *Queries) GetSessionContextByToken(ctx context.Context, token string) (GetSessionContextByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionContextByToken, token)
	var i GetSessionContextByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.ActiveOrganizationRole,
	)
	return i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id FROM "session" WHERE user_id = $1 AND expires_at > NOW() ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.UserID,
			&i.ImpersonatedBy,
			&i.ActiveOrganizationID,
			&i.ActiveTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionActiveOrganization = `-- name: UpdateSessionActiveOrganization :one
UPDATE "session" s
SET active_organization_id = $2, active_team_id = NULL, updated_at = NOW()
WHERE s.token = $1
  AND s.user_id = $3
  AND s.expires_at > NOW()
  AND EXISTS (
      SELECT 1 FROM "organization" o
      WHERE o.id = $2
        AND (
          EXISTS (
            SELECT 1 FROM "member" m
            WHERE m.organization_id = o.id AND m.user_id = $3
          )
          OR EXISTS (
            SELECT 1 FROM "user" u
            WHERE u.id = $3 AND u.role = 'admin'
          )
        )
  )
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id
`

type UpdateSessionActiveOrganizationParams struct {
	Token                string      `json:"token"`
	ActiveOrganizationID pgtype.Text `json:"active_organization_id"`
	UserID               string      `json:"user_id"`
}

func (q *Queries) UpdateSessionActiveOrganization(ctx context.Context, arg UpdateSessionActiveOrganizationParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionActiveOrganization, arg.Token, arg.ActiveOrganizationID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
	)
	return i, err
}
