// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_member.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO "team_member" (id, team_id, user_id, created_at) VALUES ($1, $2, $3, NOW()) RETURNING id, team_id, user_id, created_at
`

type CreateTeamMemberParams struct {
	ID     string `json:"id"`
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.ID, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM "team_member" WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	return err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, team_id, user_id, created_at FROM "team_member" WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.created_at, u.name, u.email FROM "team_member" tm
JOIN "user" u ON u.id = tm.user_id
WHERE tm.team_id = $1 ORDER BY u.name
`

type ListTeamMembersRow struct {
	ID        string             `json:"id"`
	TeamID    string             `json:"team_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
