// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO "verification" (id, identifier, value, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, identifier, value, expires_at, created_at, updated_at
`

type CreateVerificationParams struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, createVerification,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
	)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredVerifications = `-- name: DeleteExpiredVerifications :exec
DELETE FROM "verification" WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerifications)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM "verification" WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const getVerification = `-- name: GetVerification :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM "verification" WHERE identifier = $1 AND value = $2
`

type GetVerificationParams struct {
	Identifier string `json:"identifier"`
	Value      string `json:"value"`
}

func (q *Queries) GetVerification(ctx context.Context, arg GetVerificationParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerification, arg.Identifier, arg.Value)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
